# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-12 08:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("room", "0018_auto_20161207_0844")]

    operations = [
        migrations.CreateModel(
            name="RoomClass",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="name")),
                ("has_variants", models.BooleanField(default=True)),
                (
                    "room_attributes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="rooms_class",
                        to="room.RoomAttribute",
                    ),
                ),
                (
                    "variant_attributes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="room_variants_class",
                        to="room.RoomAttribute",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="room_class",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="room.RoomClass",
            ),
        ),
    ]
