# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-13 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("room", "0026_auto_20161230_0347")]

    operations = [
        migrations.AlterField(
            model_name="roomclass",
            name="has_variants",
            field=models.BooleanField(default=True, verbose_name="has variants"),
        ),
        migrations.AlterField(
            model_name="roomclass",
            name="is_shipping_required",
            field=models.BooleanField(
                default=False, verbose_name="is shipping required"
            ),
        ),
        migrations.AlterField(
            model_name="roomclass",
            name="room_attributes",
            field=models.ManyToManyField(
                blank=True,
                related_name="rooms_class",
                to="room.RoomAttribute",
                verbose_name="room attributes",
            ),
        ),
        migrations.AlterField(
            model_name="roomclass",
            name="variant_attributes",
            field=models.ManyToManyField(
                blank=True,
                related_name="room_variants_class",
                to="room.RoomAttribute",
                verbose_name="variant attributes",
            ),
        ),
        migrations.AlterField(
            model_name="stocklocation",
            name="name",
            field=models.CharField(max_length=100, verbose_name="location"),
        ),
    ]
