# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("room", "0030_auto_20170206_0407")]

    operations = [
        migrations.RemoveField(model_name="room", name="weight"),
        migrations.RemoveField(model_name="roomvariant", name="weight_override"),
    ]
