# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("room", "0034_room_is_published")]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "permissions": (
                    ("view_category", "Can view categories"),
                    ("edit_category", "Can edit categories"),
                ),
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
        migrations.AlterModelOptions(
            name="room",
            options={
                "permissions": (
                    ("view_room", "Can view rooms"),
                    ("edit_room", "Can edit rooms"),
                ),
                "verbose_name": "room",
                "verbose_name_plural": "rooms",
            },
        ),
        migrations.AlterModelOptions(
            name="stocklocation",
            options={
                "permissions": (
                    ("view_stock_location", "Can view stock location"),
                    ("edit_stock_location", "Can edit stock location"),
                )
            },
        ),
    ]
