# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-15 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("room", "0035_auto_20170919_0846")]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={
                "permissions": (
                    ("view_room", "Can view rooms"),
                    ("edit_room", "Can edit rooms"),
                    ("view_properties", "Can view room properties"),
                    ("edit_properties", "Can edit room properties"),
                ),
                "verbose_name": "room",
                "verbose_name_plural": "rooms",
            },
        )
    ]
