# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-30 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0038_auto_20171129_0616"),
        ("room", "0037_auto_20171129_1004"),
    ]

    operations = []
