# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-08 14:14
from __future__ import unicode_literals

from decimal import Decimal

import django.contrib.postgres.fields.hstore
import django.core.validators
import django.db.models.deletion
import versatileimagefield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("room", "0043_auto_20171207_0839")]

    operations = [
        migrations.AlterField(
            model_name="attributechoicevalue",
            name="color",
            field=models.CharField(
                blank=True,
                max_length=7,
                validators=[
                    django.core.validators.RegexValidator(
                        "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="attributechoicevalue",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="is_hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="category", name="name", field=models.CharField(max_length=128)
        ),
        migrations.AlterField(
            model_name="category",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="room.Category",
            ),
        ),
        migrations.AlterField(
            model_name="category", name="slug", field=models.SlugField()
        ),
        migrations.AlterField(
            model_name="room",
            name="attributes",
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
        migrations.AlterField(
            model_name="room",
            name="available_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="room",
            name="categories",
            field=models.ManyToManyField(
                related_name="rooms", to="room.Category"
            ),
        ),
        migrations.AlterField(
            model_name="room", name="description", field=models.TextField()
        ),
        migrations.AlterField(
            model_name="room",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="room",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="room", name="name", field=models.CharField(max_length=128)
        ),
        migrations.AlterField(
            model_name="room",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="room.RoomClass",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="roomattribute",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="roomattribute",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name="roomclass",
            name="has_variants",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="roomclass",
            name="is_shipping_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="roomclass",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="roomclass",
            name="room_attributes",
            field=models.ManyToManyField(
                blank=True, related_name="rooms_class", to="room.RoomAttribute"
            ),
        ),
        migrations.AlterField(
            model_name="roomclass",
            name="variant_attributes",
            field=models.ManyToManyField(
                blank=True,
                related_name="room_variants_class",
                to="room.RoomAttribute",
            ),
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="alt",
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="image",
            field=versatileimagefield.fields.VersatileImageField(upload_to="rooms"),
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="order",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="ppoi",
            field=versatileimagefield.fields.PPOIField(
                default="0.5x0.5", editable=False, max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="room.Room",
            ),
        ),
        migrations.AlterField(
            model_name="roomvariant",
            name="attributes",
            field=django.contrib.postgres.fields.hstore.HStoreField(default={}),
        ),
        migrations.AlterField(
            model_name="roomvariant",
            name="images",
            field=models.ManyToManyField(
                through="room.VariantImage", to="room.RoomImage"
            ),
        ),
        migrations.AlterField(
            model_name="roomvariant",
            name="name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="roomvariant",
            name="price_override",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="roomvariant",
            name="sku",
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="cost_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.IntegerField(
                default=Decimal("1"),
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="quantity_allocated",
            field=models.IntegerField(
                default=Decimal("0"),
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock",
                to="room.RoomVariant",
            ),
        ),
        migrations.AlterField(
            model_name="stocklocation",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="variantimage",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_images",
                to="room.RoomImage",
            ),
        ),
        migrations.AlterField(
            model_name="variantimage",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_images",
                to="room.RoomVariant",
            ),
        ),
    ]
