# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-15 11:16
from __future__ import unicode_literals

from django.db import migrations
from markdown import markdown


def md_to_html(apps, schema_editor):
    Room = apps.get_model("room", "Room")
    for room in Room.objects.all():
        room.description = markdown(room.description)
        room.save()


class Migration(migrations.Migration):
    dependencies = [("room", "0044_auto_20180108_0814")]

    operations = [migrations.RunPython(md_to_html, migrations.RunPython.noop)]
