# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 11:56
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


def assign_category_to_rooms(apps, schema_editor):
    Room = apps.get_model("room", "Room")
    for room in Room.objects.all():
        room.category = room.categories.first()
        room.save()


def assign_categories_to_rooms(apps, schema_editor):
    Room = apps.get_model("room", "Room")
    for room in Room.objects.all():
        if room.category:
            room.categories.add(room.category)


class Migration(migrations.Migration):

    dependencies = [("room", "0045_md_to_html")]

    operations = [
        migrations.AddField(
            model_name="room",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="room.Category",
            ),
        ),
        migrations.RunPython(
            assign_category_to_rooms, assign_categories_to_rooms
        ),
    ]
