# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 09:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("room", "0046_room_category")]

    operations = [
        migrations.RemoveField(model_name="category", name="is_hidden"),
        migrations.RemoveField(model_name="room", name="categories"),
        migrations.AlterField(
            model_name="room",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rooms",
                to="room.Category",
            ),
        ),
    ]
