# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-15 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("room", "0047_auto_20180117_0359")]

    operations = [
        migrations.RenameModel(old_name="RoomClass", new_name="RoomType"),
        migrations.RenameField(
            model_name="room", old_name="room_class", new_name="room_type"
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="room_attributes",
            field=models.ManyToManyField(
                blank=True, related_name="room_types", to="room.RoomAttribute"
            ),
        ),
        migrations.AlterField(
            model_name="roomtype",
            name="variant_attributes",
            field=models.ManyToManyField(
                blank=True,
                related_name="room_variant_types",
                to="room.RoomAttribute",
            ),
        ),
    ]
