# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-24 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("room", "0048_room_class_to_type")]

    operations = [
        migrations.CreateModel(
            name="CollectionRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
            options={"db_table": "room_collection_rooms"},
        ),
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, unique=True)),
                ("slug", models.SlugField()),
                (
                    "rooms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collections",
                        through="room.CollectionRoom",
                        to="room.Room",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="collectionroom",
            name="collection",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE, to="room.Collection"
            ),
        ),
        migrations.AddField(
            model_name="collectionroom",
            name="room",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE, to="room.Room"
            ),
        ),
    ]
