# Generated by Django 2.0.3 on 2018-03-20 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0053_room_seo_description"),
        ("room", "0053_auto_20180305_1002"),
    ]

    operations = []
