# Generated by Django 2.0.3 on 2018-05-08 16:05

from django.db import migrations, models


def assign_sort_order_to_room_images(apps, schema_editor):
    RoomAttribute = apps.get_model("room", "RoomAttribute")
    for attribute in RoomAttribute.objects.prefetch_related("values"):
        for order, value in enumerate(attribute.values.all()):
            value.sort_order = order
            value.save()


class Migration(migrations.Migration):

    dependencies = [("room", "0061_room_taxes")]

    operations = [
        migrations.AlterModelOptions(
            name="attributechoicevalue", options={"ordering": ("sort_order",)}
        ),
        migrations.AddField(
            model_name="attributechoicevalue",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterModelOptions(
            name="roomimage", options={"ordering": ("sort_order",)}
        ),
        migrations.RenameField(
            model_name="roomimage", old_name="order", new_name="sort_order"
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
        migrations.RemoveField(model_name="attributechoicevalue", name="color"),
        migrations.RunPython(
            assign_sort_order_to_room_images, migrations.RunPython.noop
        ),
    ]
