# Generated by Django 2.0.3 on 2018-07-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("room", "0064_roomvariant_handle_stock")]

    operations = [
        migrations.AlterModelOptions(name="category", options={}),
        migrations.AlterModelOptions(
            name="room",
            options={"permissions": (("manage_rooms", "Manage rooms."),)},
        ),
    ]
