# Generated by Django 2.0.3 on 2018-08-22 12:20

import django_measurement.models
from django.db import migrations

import vanphong.core.weight


class Migration(migrations.Migration):

    dependencies = [("room", "0067_remove_room_is_featured")]

    operations = [
        migrations.AddField(
            model_name="room",
            name="weight",
            field=django_measurement.models.MeasurementField(
                blank=True, measurement_class="Mass", null=True
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="weight",
            field=django_measurement.models.MeasurementField(
                default=vanphong.core.weight.zero_weight, measurement_class="Mass"
            ),
        ),
        migrations.AddField(
            model_name="roomvariant",
            name="weight",
            field=django_measurement.models.MeasurementField(
                blank=True, measurement_class="Mass", null=True
            ),
        ),
    ]
