# Generated by Django 2.1.2 on 2018-10-10 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("room", "0074_auto_20181010_0730")]

    operations = [
        migrations.RemoveField(model_name="roomtype", name="room_attributes"),
        migrations.RemoveField(model_name="roomtype", name="variant_attributes"),
        migrations.AlterField(
            model_name="attribute",
            name="room_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_attributes",
                to="room.RoomType",
            ),
        ),
        migrations.AlterField(
            model_name="attribute",
            name="room_variant_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variant_attributes",
                to="room.RoomType",
            ),
        ),
    ]
