# Generated by Django 2.1.3 on 2018-12-15 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0080_collection_published_date"),
        ("room", "0080_auto_20181214_0440"),
    ]

    operations = []
