# Generated by Django 2.2.1 on 2019-05-21 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("room", "0092_auto_20190507_0309")]

    operations = [
        migrations.AddField(
            model_name="collectionroom",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="collectionroom",
            name="room",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="collectionroom",
                to="room.Room",
            ),
        ),
        migrations.AlterField(
            model_name="collectionroom",
            name="collection",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="collectionroom",
                to="room.Collection",
            ),
        ),
        migrations.AlterModelTable(name="collectionroom", table=None),
        migrations.AlterField(
            model_name="attributevalue",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="roomimage",
            name="sort_order",
            field=models.PositiveIntegerField(db_index=True, editable=False, null=True),
        ),
    ]
