# Generated by Django 3.0.6 on 2020-05-27 08:14

from django.db import migrations, models


def populate_room_variant_price(apps, schema_editor):
    RoomVariant = apps.get_model("room", "RoomVariant")
    for room_variant in RoomVariant.objects.iterator():
        price_override_amount = room_variant.price_override_amount
        if price_override_amount:
            room_variant.price_amount = price_override_amount
        else:
            room_price = room_variant.room.price_amount
            room_variant.price_amount = room_price

        room_variant.save(update_fields=["price_amount"])


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0117_auto_20200423_0737"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomvariant",
            name="price_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.RunPython(populate_room_variant_price),
        migrations.AlterField(
            model_name="roomvariant",
            name="price_amount",
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.RemoveField(
            model_name="roomvariant",
            name="price_override_amount",
        ),
        migrations.RemoveField(
            model_name="room",
            name="price_amount",
        ),
        migrations.AlterField(
            model_name="room",
            name="minimal_variant_price_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
