# Generated by Django 3.1.1 on 2020-09-22 11:49

import django.db.models.deletion
from django.db import migrations, models


def set_default_variants(apps, schema_editor):
    Room = apps.get_model("room", "Room")
    for room in Room.objects.iterator():
        first_variant = room.variants.first()
        if first_variant:
            room.default_variant = first_variant
            room.save(update_fields=["default_variant", "updated_at"])


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0125_auto_20200916_1511"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="default_variant",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to="room.roomvariant",
            ),
        ),
        migrations.RunPython(
            set_default_variants, reverse_code=migrations.RunPython.noop
        ),
    ]
