# Generated by Django 3.1.2 on 2020-10-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0131_auto_20201112_0904"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
