# Generated by Django 3.1 on 2020-08-19 07:50

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def migrate_rooms_publishable_data(apps, schema_editor):
    Channel = apps.get_model("channel", "Channel")
    Room = apps.get_model("room", "Room")
    RoomChannelListing = apps.get_model("room", "RoomChannelListing")

    channels_dict = {}

    for room in Room.objects.iterator():
        currency = room.currency
        channel = channels_dict.get(currency)
        if not channel:
            name = f"Channel {currency}"
            channel, _ = Channel.objects.get_or_create(
                currency_code=currency,
                defaults={"name": name, "slug": slugify(name)},
            )
            channels_dict[currency] = channel
        RoomChannelListing.objects.create(
            room=room,
            channel=channel,
            is_published=room.is_published,
            publication_date=room.publication_date,
            currency=currency,
            visible_in_listings=room.visible_in_listings,
            available_for_purchase=room.available_for_purchase,
            discounted_price_amount=room.minimal_variant_price_amount,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("channel", "0001_initial"),
        ("room", "0133_room_variant_channel_listing"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoomChannelListing",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publication_date", models.DateField(blank=True, null=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "channel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_listings",
                        to="channel.channel",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_listings",
                        to="room.room",
                    ),
                ),
                (
                    "discounted_price_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                    ),
                ),
                ("currency", models.CharField(max_length=3)),
                ("visible_in_listings", models.BooleanField(default=False)),
                ("available_for_purchase", models.DateField(blank=True, null=True)),
            ],
            options={"ordering": ("pk",), "unique_together": {("room", "channel")}},
        ),
        migrations.RunPython(migrate_rooms_publishable_data),
        migrations.RemoveField(
            model_name="room",
            name="is_published",
        ),
        migrations.RemoveField(
            model_name="room",
            name="publication_date",
        ),
        migrations.RemoveField(
            model_name="room",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="room",
            name="minimal_variant_price_amount",
        ),
        migrations.RemoveField(
            model_name="room",
            name="visible_in_listings",
        ),
        migrations.RemoveField(
            model_name="room",
            name="available_for_purchase",
        ),
    ]
