# Generated by Django 3.1.5 on 2021-01-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0137_drop_attribute_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='roomtype',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='roomvariant',
            name='weight',
        ),
    ]
