# Generated by Django 3.1.5 on 2021-01-28 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0138_auto_20210126_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='is_shipping_required',
        ),
    ]
