# Generated by Django 3.1.5 on 2021-01-28 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0139_remove_roomtype_is_shipping_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomtype',
            name='is_digital',
        ),
    ]
