# Generated by Django 3.1.5 on 2021-01-26 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0097_auto_20210107_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='weight',
        ),
    ]
