# Generated by Django 3.1.5 on 2021-01-15 13:07

from django.db import migrations, models

import vanphong.core.utils.json_serializer


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0011_auto_20200714_0539"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=vanphong.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="hotel",
            name="private_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                encoder=vanphong.core.utils.json_serializer.CustomJsonEncoder,
                null=True,
            ),
        ),
    ]
