# Generated by Django 3.1.5 on 2021-01-29 03:43

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_remove_hotel_shipping_zones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ('-name',)},
        ),
        migrations.AddField(
            model_name='hotel',
            name='cover_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='hotel-cover-images'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='hotel',
            name='detail',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='distance',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='payment',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_per_hour_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='hotel',
            name='price_per_night_amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='hotel',
            name='star_rating',
            field=models.PositiveIntegerField(blank=True, default=2),
        ),
    ]
