# Generated by Django 2.0.3 on 2018-07-18 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("room", "0064_roomvariant_handle_stock"),
        ("discount", "0007_auto_20180108_0814"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="collections",
            field=models.ManyToManyField(blank=True, to="room.Collection"),
        )
    ]
