# Generated by Django 3.0.6 on 2020-10-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256)),
                ('city', models.CharField(blank=True, max_length=256)),
                ('featured_image', models.CharField(blank=True, max_length=256)),
            ],
            options={
                'ordering': ('pk',),
            },
        ),
    ]
