# Generated by Django 3.0.6 on 2020-10-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='city',
            new_name='country',
        ),
        migrations.AddField(
            model_name='place',
            name='hotels',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='place',
            name='place_type',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='place',
            name='province',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
