# Generated by Django 3.1 on 2020-10-30 11:28

import django.db.models.deletion
from django.db import migrations, models

import saleor.core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("room", "0136_add_attribute_type_and_page_to_attribute_relation"),
        ("page", "0017_pagetype"),
    ]

    state_operations = [
        migrations.CreateModel(
            name="AssignedPageAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"db_table": "room_assignedpageattribute"},
        ),
        migrations.CreateModel(
            name="AssignedRoomAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"db_table": "room_assignedroomattribute"},
        ),
        migrations.CreateModel(
            name="AssignedVariantAttribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={"db_table": "room_assignedvariantattribute"},
        ),
        migrations.CreateModel(
            name="Attribute",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "private_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        encoder=saleor.core.utils.json_serializer.CustomJsonEncoder,
                        null=True,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=250, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("room-type", "Room type"),
                            ("page-type", "Page type"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "input_type",
                    models.CharField(
                        choices=[
                            ("dropdown", "Dropdown"),
                            ("multiselect", "Multi Select"),
                        ],
                        default="dropdown",
                        max_length=50,
                    ),
                ),
                ("value_required", models.BooleanField(blank=True, default=False)),
                ("is_variant_only", models.BooleanField(blank=True, default=False)),
                (
                    "visible_in_storefront",
                    models.BooleanField(blank=True, default=True),
                ),
                (
                    "filterable_in_storefront",
                    models.BooleanField(blank=True, default=True),
                ),
                (
                    "filterable_in_dashboard",
                    models.BooleanField(blank=True, default=True),
                ),
                (
                    "storefront_search_position",
                    models.IntegerField(blank=True, default=0),
                ),
                ("available_in_grid", models.BooleanField(blank=True, default=True)),
            ],
            options={
                "db_table": "room_attribute",
                "ordering": ("storefront_search_position", "slug"),
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(db_index=True, editable=False, null=True),
                ),
                ("name", models.CharField(max_length=250)),
                ("value", models.CharField(blank=True, default="", max_length=100)),
                ("slug", models.SlugField(allow_unicode=True, max_length=255)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="attribute.attribute",
                    ),
                ),
            ],
            options={
                "db_table": "room_attributevalue",
                "ordering": ("sort_order", "pk"),
                "unique_together": {("slug", "attribute")},
            },
        ),
        migrations.CreateModel(
            name="AttributeVariant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(db_index=True, editable=False, null=True),
                ),
                (
                    "assigned_variants",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attributesrelated",
                        through="attribute.AssignedVariantAttribute",
                        to="room.RoomVariant",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributevariant",
                        to="attribute.attribute",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributevariant",
                        to="room.roomtype",
                    ),
                ),
            ],
            options={
                "db_table": "room_attributevariant",
                "ordering": ("sort_order", "pk"),
                "unique_together": {("attribute", "room_type")},
            },
        ),
        migrations.CreateModel(
            name="AttributeRoom",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(db_index=True, editable=False, null=True),
                ),
                (
                    "assigned_rooms",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attributesrelated",
                        through="attribute.AssignedRoomAttribute",
                        to="room.Room",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributeroom",
                        to="attribute.attribute",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributeroom",
                        to="room.roomtype",
                    ),
                ),
            ],
            options={
                "db_table": "room_attributeroom",
                "ordering": ("sort_order", "pk"),
                "unique_together": {("attribute", "room_type")},
            },
        ),
        migrations.CreateModel(
            name="AttributePage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sort_order",
                    models.IntegerField(db_index=True, editable=False, null=True),
                ),
                (
                    "assigned_pages",
                    models.ManyToManyField(
                        blank=True,
                        related_name="attributesrelated",
                        through="attribute.AssignedPageAttribute",
                        to="page.Page",
                    ),
                ),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributepage",
                        to="attribute.attribute",
                    ),
                ),
                (
                    "page_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributepage",
                        to="page.pagetype",
                    ),
                ),
            ],
            options={
                "db_table": "room_attributepage",
                "ordering": ("sort_order", "pk"),
                "unique_together": {("attribute", "page_type")},
            },
        ),
        migrations.AddField(
            model_name="attribute",
            name="page_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="page_attributes",
                through="attribute.AttributePage",
                to="page.PageType",
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="room_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="room_attributes",
                through="attribute.AttributeRoom",
                to="room.RoomType",
            ),
        ),
        migrations.AddField(
            model_name="attribute",
            name="room_variant_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="variant_attributes",
                through="attribute.AttributeVariant",
                to="room.RoomType",
            ),
        ),
        migrations.AddField(
            model_name="assignedvariantattribute",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variantassignments",
                to="attribute.attributevariant",
            ),
        ),
        migrations.AddField(
            model_name="assignedvariantattribute",
            name="values",
            field=models.ManyToManyField(to="attribute.AttributeValue"),
        ),
        migrations.AddField(
            model_name="assignedvariantattribute",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="room.roomvariant",
            ),
        ),
        migrations.AddField(
            model_name="assignedroomattribute",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roomassignments",
                to="attribute.attributeroom",
            ),
        ),
        migrations.AddField(
            model_name="assignedroomattribute",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="room.room",
            ),
        ),
        migrations.AddField(
            model_name="assignedroomattribute",
            name="values",
            field=models.ManyToManyField(to="attribute.AttributeValue"),
        ),
        migrations.AddField(
            model_name="assignedpageattribute",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pageassignments",
                to="attribute.attributepage",
            ),
        ),
        migrations.AddField(
            model_name="assignedpageattribute",
            name="page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attributes",
                to="page.page",
            ),
        ),
        migrations.AddField(
            model_name="assignedpageattribute",
            name="values",
            field=models.ManyToManyField(to="attribute.AttributeValue"),
        ),
        migrations.CreateModel(
            name="AttributeValueTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                (
                    "attribute_value",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="attribute.attributevalue",
                    ),
                ),
            ],
            options={
                "db_table": "room_attributevaluetranslation",
                "unique_together": {("language_code", "attribute_value")},
            },
        ),
        migrations.CreateModel(
            name="AttributeTranslation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_code", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="attribute.attribute",
                    ),
                ),
            ],
            options={
                "db_table": "room_attributetranslation",
                "unique_together": {("language_code", "attribute")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="assignedvariantattribute",
            unique_together={("variant", "assignment")},
        ),
        migrations.AlterUniqueTogether(
            name="assignedroomattribute",
            unique_together={("room", "assignment")},
        ),
        migrations.AlterUniqueTogether(
            name="assignedpageattribute",
            unique_together={("page", "assignment")},
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(state_operations=state_operations)
    ]
