# Generated by Django 3.1.5 on 2021-01-28 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0028_delete_authorizationkey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='charge_taxes_on_shipping',
        ),
    ]
