# Generated by Django 3.1.5 on 2021-01-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site', '0029_remove_sitesettings_charge_taxes_on_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='default_weight_unit',
        ),
    ]
