# Generated by Django 3.1.5 on 2021-01-28 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0030_checkout_channel_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='shipping_method',
        ),
    ]
